module.exports = (dataServices) => ({
    users : require('./users')(dataServices),
    roles : require('./roles')(dataServices),
    permissions : require('./permissions')(dataServices),
    rolePermissions : require('./rolePermissions')(dataServices),
    userRoles : require('./userRoles')(dataServices),
    certificates : require('./certificates')(dataServices),
    specialtyDetail : require('./specialtyDetail')(dataServices),
    drugs : require('./drugs')(dataServices),
    inputs : require('./inputs')(dataServices),
    batches : require('./batches')(dataServices),
    purchaseDetails : require('./purchaseDetails')(dataServices),
    transferDetails : require('./transferDetails')(dataServices),
    outputs : require('./outputs')(dataServices),
    patients : require('./patients')(dataServices),
    prescriptions : require('./prescriptions')(dataServices),
    prescriptionDrugs : require('./prescriptionDrugs')(dataServices),
    prescriptionFills : require('./prescriptionFills')(dataServices),
    prescriptionReturns : require('./prescriptionReturns')(dataServices),
});
